#!/usr/bin/env bash
# Idempotently provision the three GearSnitch web subscription tiers in Stripe.
#
# Requires the `stripe` CLI authenticated against the target account
# (`stripe login`, then verify with `stripe config --list`).
#
# Re-running this script is safe: it looks up existing Products by metadata
# `gearsnitch_tier=<tier>` and only creates them if missing. Prices are
# similarly looked up by their (product, recurring.interval, unit_amount,
# currency) tuple before being created.
#
# Output: writes the resulting Price IDs to `api/src/config/stripe-prices.json`
# (gitignored — DO NOT commit the live IDs). Export the values into the API
# environment as STRIPE_PRICE_HUSTLE / STRIPE_PRICE_HWMF / STRIPE_PRICE_BABY_MOMMA.
#
# Usage:
#   stripe login                       # one-time
#   ./scripts/setup-stripe-products.sh
#   # then copy the printed env vars into your secret store

set -euo pipefail

if ! command -v stripe >/dev/null 2>&1; then
  echo "error: 'stripe' CLI not found. Install: https://stripe.com/docs/stripe-cli" >&2
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "error: 'jq' not found. brew install jq" >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="${REPO_ROOT}/api/src/config/stripe-prices.json"
mkdir -p "$(dirname "$OUT_FILE")"

# tier_key | display_name | description | mode (recurring|one_time) | interval | unit_amount_cents | currency | metadata_value
TIERS=(
  "hustle|GearSnitch HUSTLE|Monthly Pro plan|recurring|month|499|usd|hustle"
  "hwmf|GearSnitch HWMF|Annual Pro plan (Have What My Friends have)|recurring|year|6000|usd|hwmf"
  "babyMomma|GearSnitch BABY MOMMA|Lifetime Pro access|one_time||9900|usd|babyMomma"
)

declare -A PRICE_IDS

for ROW in "${TIERS[@]}"; do
  IFS='|' read -r KEY NAME DESC MODE INTERVAL AMOUNT CURRENCY META <<<"$ROW"

  echo ""
  echo "==> Provisioning ${KEY} (${NAME})"

  # Look for an existing product by metadata.gearsnitch_tier=$META
  # `stripe products search` requires structured search — fall back to listing.
  PRODUCT_ID=$(stripe products list --limit 100 \
    | jq -r --arg meta "$META" '.data[] | select(.metadata.gearsnitch_tier==$meta) | .id' \
    | head -n1 || true)

  if [[ -z "${PRODUCT_ID}" ]]; then
    echo "    creating Product…"
    PRODUCT_ID=$(stripe products create \
      --name "$NAME" \
      --description "$DESC" \
      -d "metadata[gearsnitch_tier]=$META" \
      | jq -r '.id')
    echo "    created product $PRODUCT_ID"
  else
    echo "    reusing existing product $PRODUCT_ID"
  fi

  # Look for an existing matching Price.
  if [[ "$MODE" == "recurring" ]]; then
    PRICE_ID=$(stripe prices list --product "$PRODUCT_ID" --active true --limit 100 \
      | jq -r --arg amt "$AMOUNT" --arg cur "$CURRENCY" --arg int "$INTERVAL" \
        '.data[] | select(.unit_amount==($amt|tonumber)) | select(.currency==$cur) | select(.recurring.interval==$int) | .id' \
      | head -n1 || true)
  else
    PRICE_ID=$(stripe prices list --product "$PRODUCT_ID" --active true --limit 100 \
      | jq -r --arg amt "$AMOUNT" --arg cur "$CURRENCY" \
        '.data[] | select(.unit_amount==($amt|tonumber)) | select(.currency==$cur) | select(.recurring==null) | .id' \
      | head -n1 || true)
  fi

  if [[ -z "${PRICE_ID}" ]]; then
    echo "    creating Price…"
    if [[ "$MODE" == "recurring" ]]; then
      PRICE_ID=$(stripe prices create \
        --product "$PRODUCT_ID" \
        --unit-amount "$AMOUNT" \
        --currency "$CURRENCY" \
        -d "recurring[interval]=$INTERVAL" \
        -d "metadata[gearsnitch_tier]=$META" \
        | jq -r '.id')
    else
      PRICE_ID=$(stripe prices create \
        --product "$PRODUCT_ID" \
        --unit-amount "$AMOUNT" \
        --currency "$CURRENCY" \
        -d "metadata[gearsnitch_tier]=$META" \
        | jq -r '.id')
    fi
    echo "    created price $PRICE_ID"
  else
    echo "    reusing existing price $PRICE_ID"
  fi

  PRICE_IDS[$KEY]="$PRICE_ID"
done

cat > "$OUT_FILE" <<EOF
{
  "_comment": "Generated by scripts/setup-stripe-products.sh — DO NOT COMMIT to git. Export these as STRIPE_PRICE_* env vars.",
  "hustle":     "${PRICE_IDS[hustle]}",
  "hwmf":       "${PRICE_IDS[hwmf]}",
  "babyMomma":  "${PRICE_IDS[babyMomma]}"
}
EOF

echo ""
echo "Wrote: $OUT_FILE"
echo ""
echo "Add these to your API environment (Cloud Run secret manager / .env):"
echo ""
echo "  STRIPE_PRICE_HUSTLE=${PRICE_IDS[hustle]}"
echo "  STRIPE_PRICE_HWMF=${PRICE_IDS[hwmf]}"
echo "  STRIPE_PRICE_BABY_MOMMA=${PRICE_IDS[babyMomma]}"
echo ""
echo "Then configure the webhook endpoint:"
echo "  https://api.gearsnitch.com/api/v1/subscriptions/stripe/webhook"
echo "  (or the existing /api/v1/store/payments/webhook — both handle subscription events)"
echo ""
echo "Subscribe to events:"
echo "  checkout.session.completed"
echo "  customer.subscription.created"
echo "  customer.subscription.updated"
echo "  customer.subscription.deleted"
echo "  invoice.paid"
echo "  invoice.payment_succeeded"
echo "  invoice.payment_failed"
